### ISSUE TITLE
Question about readme provenance

### ISSUE THREAD

**Issue by cthoyt** [schwallergroup/chaos#2]
I'm curious how you chose to format your README. It has some of the telltale headers and emojis of one of my repos, so I'm curious if you based it off of one of mine, or if there's a deeper trail of borrowing going on

**Comment by bojana-rankovic** [comment]
Hi @cthoyt,
Thank you for noticing the similarities! We’re glad you reached out. Indeed, we started off with pyscaffold and then took some inspiration from the [schwallergroup/liac-repo](https://github.com/schwallergroup/liac-repo), which utilizes the snekpack structure. It’s a great setup that we really liked.
We’ll be sure to reference snekpack in our documentation to acknowledge its influence on our formatting. Thanks for your contributions to the community!
